spring.application.name=RETO6-DI

# Propiedades corregidas con .data.
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
springdoc.swagger-ui.tags-sorter=alpha